name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install .[dev]
    - name: Run style checks
      run: |
        make check-codestyle
    - name: Publish package
      env:
        PYPI_USERNAME: __token__
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        make publish
